import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip"
import { AppSidebar } from "@/components/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>
        {/* <TooltipProvider>{children}</TooltipProvider> */}
        <SidebarProvider>
      <SidebarInset>
        <header className="flex h-16 items-center  px-4">
          <Navbar/>
          <SidebarTrigger className="ml-auto rotate-180" />
        </header>

        <main className="flex-1">
          {children}
        </main>
      </SidebarInset>

      <AppSidebar side="right" />
    </SidebarProvider>
    <Footer/>
      </body>
    </html>
  )
}